# Generated by Django 3.2 on 2023-06-25 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20230625_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unique_key',
        ),
    ]
