# Generated by Django 3.2 on 2023-06-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiredmedecines',
            name='product',
        ),
    ]
