# Generated by Django 3.2 on 2023-06-25 08:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_expiredmedecines_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unique_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
