# Generated by Django 3.2 on 2023-07-26 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredmedecines',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
