# Generated by Django 3.2 on 2023-07-26 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_expiredmedecines_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredmedecines',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
